language: python
cache: pip
python:
  - "3.8"
  - "3.7"
  - "3.6"
  - "3.5"
  - "3.4"
install:
  - pip install .[test]
script:
  - if [[ $TRAVIS_PYTHON_VERSION != 3.5 ]] && [[ $TRAVIS_PYTHON_VERSION != 3.4 ]]; then black --check *.py */; fi
  - isort --check-only --recursive *.py */
  - flake8
  - python -m pytest tests/
